### ISSUE TITLE
STLs lose position when saving a project multiple times

### ISSUE THREAD

**Issue by AESjay** [ORNLSlicer/Slicer-2#26]
## Expected Behavior
STLs maintain position when projects are saved and re-opened multiple times.

## Actual Behavior
STLs move position after 2nd time saving a project file, even when saving with a new name.  Reference email from Jay 12/20/23 for details and example projects of this behavior.

@aroschli  @mborish 
Bug  Core  HIGH priority

**Comment by aroschli** [comment]
Bug has been resolved
