### ISSUE TITLE
gCode Visualization on Variable Z

### ISSUE THREAD

**Issue by AESjack** [ORNLSlicer/Slicer-2#28]
## Expected Behavior
Parsing gCode in the editor section through all layers that are sliced and present in the code.
## Actual Behavior
When the "Upper Layer" reaches the W limit of the BAAM (95") and the Z begins to be used for layer changes the visualization stops showing the layers stacking. The layers instead start to display on top of each other for the remainder of the code.

## Steps to Reproduce the Problem

- Import gCode sliced using variable Z that builds above the W limit of the machine forcing it to use Z moves for top layers.

![image](https://github.com/ORNLSlicer/Slicer-2/assets/97740120/4dfd3080-6750-4073-b618-a58bf45e894c)

![image](https://github.com/ORNLSlicer/Slicer-2/assets/97740120/8b71da2a-b8fb-4096-97ce-4876b57a47a0)

![image](https://github.com/ORNLSlicer/Slicer-2/assets/97740120/e6656e0d-e574-4604-a989-6df70f1b0243)

**Comment by aroschli** [comment]
This issue has been resolved and will be part of the next release.
