### ISSUE TITLE
Pathing Exceeding STL Bounds

### ISSUE THREAD

**Issue by aroschli** [ORNLSlicer/Slicer-2#31]
## Expected Behavior
Self-Explanatory.

## Actual Behavior
![image](https://github.com/ORNLSlicer/Slicer-2/assets/24685926/f721cc27-42c0-4517-8627-4bdcb60c9e46)

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory. 

## Specifications
Platform, machine specs, anything else you think might be relevant.
[1530-0205-Test01.zip](https://github.com/ORNLSlicer/Slicer-2/files/13978584/1530-0205-Test01.zip)

**Comment by AESjay** [comment]
@aroschli - I thought this was only infill and skins, but I did see this happen last week with insets. Whole project was sliced with about 4 insets, but the tip of the print was all only 2 bead wall (perimeters).  X-section of STL looks correct. But during a print, layers 461 thru 469 all the sudden had insets and starting printing over air.  

![image](https://github.com/ORNLSlicer/Slicer-2/assets/97554389/54df0971-7a8c-405e-bea3-e626daa3f386)

![image](https://github.com/ORNLSlicer/Slicer-2/assets/97554389/5cc2ffb1-8a7e-4661-936f-e81bf29a1e84)

**Comment by aroschli** [comment]
Thanks @AESjay for the additional images. I meant to include inset in the title, but my original image also captures some instances of insets going out of the bounds.

**Comment by AESjay** [comment]
OK good, I just hadn't seen it do it with insets until then, so I wanted to
make you aware.

*Jay Evanovich*
800-210-9801 x703
Additive Engineering Solutions, LLC.

**Comment by aroschli** [comment]
Issue has been resolved and will be part of the next release.

**Comment by AESjay** [comment]
Excellent, thanks Alex.
