### ISSUE TITLE
Start/stop Optimization Not Functioning for Skeletons

### ISSUE THREAD

**Issue by AESjack** [ORNLSlicer/Slicer-2#32]
## Expected Behavior
Settings the Island/Path/Point Order Optimization to XY values to control a start/stop.

## Actual Behavior
G-Code does not reflect the XY locations specified.

## Possible Solution
N/A

## Steps to Reproduce the Problem

![1](https://github.com/ORNLSlicer/Slicer-2/assets/97740120/ca46dc0b-4df3-44bb-8b7b-bf9eef87d672)
![2](https://github.com/ORNLSlicer/Slicer-2/assets/97740120/678cf098-2944-4a0f-ba2a-548534a48ace)
![3](https://github.com/ORNLSlicer/Slicer-2/assets/97740120/df9edb97-92a0-4d2e-aa5c-c496c62a71de)
![4](https://github.com/ORNLSlicer/Slicer-2/assets/97740120/e54db4ac-0128-4909-b616-4fb33729e807)

**Comment by AESjay** [comment]
@aroschli - Yes, skeletons don't seem to respect start/stop locations which is definitely something we'd like to have control over.
