### ISSUE TITLE
Feature Request - Cumulative Print Time Total by Layer

### ISSUE THREAD

**Issue by AESjay** [ORNLSlicer/Slicer-2#34]
When viewing layer times, the normal time displays, as well as the adjusted time.  

It would be very beneficial to add another column which shows the cumulative print time to that point, for each layer. This SHOULD take into account the adjusted layer time settings.  

Reason:  Many times it is beneficial to have an operator be present for a specific part of the build, say layer 150.  The question always gets asked: how long after the print start is that?  Right now there is no way to know this easily, especially if your layer times are varying throughout the print.  However, this should be a fairly easy to implement summation since Slicer already has computed and adjusted layer times for each layer.

@aroschli @mborish 

![image](https://github.com/ORNLSlicer/Slicer-2/assets/97554389/9610cde4-3422-48ae-88ed-4661ee9fb90c)

**Comment by aroschli** [comment]
@AESjay This is a good idea and I'll see if I can take care of this at the same time as #30
